name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test "BankSystem.Tests/BankSystem.Tests.csproj" --logger "trx;LogFileName=ResultTest.trx"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: testName
        path: testPath
    - name: Download Artifacts
      uses: actions/download-artifact@v2.0.10
      with:
        path: testPath
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests          # Name of the check run which will be created
        path: testPath/ResultTest.trx   # Path to test results
        reporter: dotnet-trx        # Format of test results
