name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with dotnet
      run: dotnet test "BankSystem.Tests/BankSystem.Tests.csproj" --loger trx --results-directory ./TestResults
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.0.3
      id: trx-parser
      with:
        TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }} 


